version: "3.1"

networks:
  network:
    name: ${API_NAME}

volumes:
  data-volume:

services:
  app:
    container_name: ${API_NAME}-api
    build:
      context: "."
    command: ["npm", "run", "start"]
    env_file: ./.env.development
    volumes:
      - ./src:/app/src
    environment:
      - DB_HOST=db
    ports:
      - ${API_PORT}:${API_PORT}
    restart: on-failure:10
    depends_on:
      - db
    networks:
      - network

  db:
    image: mariadb
    restart: always
    container_name: ${API_NAME}-db
    ports:
      - ${DB_PORT}:3306
    volumes:
      - data-volume:/var/lib/mysql
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_ALLOW_EMPTY_PASSWORD: "false"
      MYSQL_DATABASE: ${DB_DATABASE}
    networks:
      - network

  doc:
    image: swaggerapi/swagger-ui
    container_name: ${API_NAME}-doc
    volumes:
      - ./docker/doc/${API_DOC_FILE}:/usr/share/nginx/html/${API_DOC_FILE}
    environment:
      - API_URL=${API_DOC_FILE}
    ports:
      - ${API_DOC_PORT}:8080
    networks:
      - network
    depends_on:
      - app

  admin:
    image: phpmyadmin
    container_name: ${API_NAME}-admin
    restart: always
    environment:
      - PMA_HOST=db
      - PMA_USER=${DB_USER}
      - PMA_PASSWORD=${DB_PASS}
    ports:
      - ${ADMIN_PORT}:80
    networks:
      - network
    depends_on:
      - db
